name: graph-sr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.2
  - pytorch=1.10
  - torchvision=0.11
  - torchaudio=0.10
  - cudatoolkit=11.3
  - cupy=9.5
  - h5py=3.3
  - ruamel.yaml
  - scikit-image=0.18
  - scipy=1.6.2
  - pip:
    - setuptools==59.5.0
    - configargparse==1.5.3
    - segmentation-models-pytorch==0.2
    - tqdm==4.62
    - tensorboard
