name: test
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11.2
  - cudatoolkit
  - h5py
  - torchvision
  - torchaudio
  - pytorch
  - pytorch-cuda=11.8
  - ruamel.yaml
  - scikit-image
  - ipykernel
  - torchmetrics
  - matplotlib
  - pip:
    - setuptools==59.5.0
    - configargparse==1.5.3
    - segmentation-models-pytorch==0.2
    - tqdm==4.62
    - tensorboard
    - wandb
    - pandas
