name: graph-sr-up
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aom
  - asttokens
  - blas
  - blas-devel
  - blosc
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - comm
  - contourpy
  - cudatoolkit
  - cupy
  - cycler
  - cytoolz
  - dask-core
  - dav1d
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - fastrlock
  - ffmpeg
  - fonttools
  - freetype
  - fsspec
  - giflib
  - gmp
  - gnutls
  - h5py
  - hdf5
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - jxrlib
  - keyutils
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libhwloc
  - libiconv
  - liblapack
  - liblapacke
  - libnghttp2
  - libnsl
  - libpng
  - libsodium
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxml2
  - libzlib
  - libzopfli
  - llvm-openmp
  - locket
  - lz4-c
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-devel
  - mkl-include
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - numpy-base
  - openh264
  - openjpeg
  - openssl
  - packaging
  - parso
  - partd
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pooch
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pygments
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-mutex
  - pywavelets
  - pyyaml
  - pyzmq
  - readline
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - scikit-image
  - scipy
  - six
  - snappy
  - stack_data
  - tbb
  - tifffile
  - tk
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - unicodedata2
  - urllib3
  - wcwidth
  - wheel
  - xorg-lib

